In [1]:
import numpy as np
import cv2
import os

In [2]:
img = np.zeros((3,3), dtype=np.uint8)

print(img)
img = cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)

img =- np.zeros((5,3),dtype=np.uint8)
print(img.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(5, 3)


In [4]:
# Demonstrate use of imshow and also scalining images


img = cv2.imread('MyPic.png',cv2.IMREAD_REDUCED_GRAYSCALE_8)
cv2.imwrite('MyPic.jpg',img)
# Using cv2.imshow() method 
# Displaying the image 
cv2.imshow('test2', img) 
  
# waits for user to press any key 
# (this is necessary to avoid Python kernel form crashing) 
cv2.waitKey(0) 
  
# closing all open windows 
cv2.destroyAllWindows() 

In [5]:
img = cv2.imread('MyPic.png',cv2.IMREAD_GRAYSCALE)
for row in np.arange(20,40):
    for col in np.arange(50,100):
        img[row,col] = 255
cv2.imshow('test',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
img = cv2.imread('MyPic.png')
my_roi = img[0:100,0:100]
cv2.imshow('test',my_roi)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img = cv2.imread('MyPic.png')
print(img.shape)
print(img.size)
print(img.dtype)

(290, 290, 3)
252300
uint8


In [15]:
# p. 35 - reading and writing video files
videoCapture = cv2.VideoCapture('MyInputVid.avi')
fps = videoCapture.get(cv2.CAP_PROP_FPS)
size = (int(videoCapture.get(cv2.CAP_PROP_FRAME_WIDTH)),
        int(videoCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
if False:
    videoWriter = cv2.VideoWriter('MyOutputVid.avi',cv2.VideoWriter_fourcc('I','4','2','0'),fps,size)
else:
    videoWriter = cv2.VideoWriter('MyOutputVid.mp4',cv2.VideoWriter_fourcc('M','P','4','V'),fps,size)
success,frame = videoCapture.read()
while success: 
    videoWriter.write(frame)
    success, frame = videoCapture.read()

OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'


In [6]:
# With the onscreen video screen active, hit "q" to quit the script
# unfortunately, I can't read the mp4 yet, even with gstreamer, as I don't have the mpr codex capability yet
# I can use uncompressed video (lik 00. 35-35), but the file size will be 10x larger than a compressed
# codex like MP4
cap = cv2.VideoCapture(0)
cap.set(3,640)
cap.set(4,480)

fourcc = cv2.VideoWriter_fourcc(*'MP4V')
out = cv2.VideoWriter('output.mp4', fourcc, 20.0, (640,480))

while(True):
    ret, frame = cap.read()
    out.write(frame)
    cv2.imshow('frame', frame)
    c = cv2.waitKey(1)
    if c & 0xFF == ord('q'):
        break

cap.release()
out.release()
cv2.destroyAllWindows()

OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'


In [43]:
# Using FPS to compute frame per second
# https://pyimagesearch.com/2015/12/21/increasing-webcam-fps-with-python-and-opencv/
from imutils.video import FPS
stream = cv2.VideoCapture(0)
fps = FPS().start()
while fps._numFrames < 100:
    (grabbed, frame) = stream.read()
    fps.update()
fps.stop()
print("Elapsed Time: {0:.2f}".format( fps.elapsed() ) )
print("Approx. FPS: {0:.2f}".format( fps.fps() ) )
stream.release()

Approx. FPS: 13.29


In [41]:
print(grabbed)
stream.release()


True
